apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector: 
    app: fungjai-webhook
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  selector:
    matchLabels:
      app: fungjai-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: fungjai-webhook
    spec:
      containers:
        - name: fungjai-webhook
          image: {{ template "webhook.image" . }}
          imagePullPolicy: IfNotPresent
          env:
          - name: MINIO_ENDPOINT
            value: {{ template "endpoint.env" . }}
          - name: MINIO_BUCKET_NAME
            value: {{ .Values.image.env.bucket }}
          - name: MINIO_LOCATION
            value: {{ .Values.image.env.location }}
          - name: MINIO_FOLDER_NAME
            value: {{ .Values.image.env.folder }}
          - name: MINIO_RESPONSE_TYPE
            value: {{ .Values.image.env.responseType }}
          envFrom:
            - secretRef:
                name: {{ .Values.image.envFrom.secretRef.name }}
          ports: 
          - containerPort: {{ .Values.deploy.containerPort }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret.name }}
      {{- end }}