apiVersion: v2
name: fungjai
description: A Helm chart for Fungjai webhook
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies: 
- name: minio
  version: 5.0.8
  repository: https://charts.min.io/