apiVersion: v1
kind: PersistentVolume
metadata:
  name: fungjai-minio
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-f92098b9:/fungjai/minio
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem