apiVersion: v1
kind: PersistentVolume
metadata:
  name: fungjai-zookeeker
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 8Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-f92098b9:/fungjai/zookeeper
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem