webhook:
  service:
    port: 1323
    targetPort: 1323
  image:
    pullSecret:
      name: regcred
    repository: 325067013020.dkr.ecr.ap-southeast-1.amazonaws.com/fungjai/webhook
    tag: "1.0.0"
    envFrom:
      secretRef:
        name: webhook-secrets
      configMapRef:
        name: webhook-configmap
  deploy:
    containerPort: 1323
  ingress:
    host: fungjai.dbiteam.com
  configMap:
    endpoint: "fungjai-minio.fungjai:9000"


clickhouse:
  enabled: true
  shards: 1
  replicaCount: 1
  auth:
    username: admin
    password: pass123
  service:
    ports:
      tcp: 9003
      https: 443
  zookeeper:
    replicaCount: 1
    persistence:
      accessModes:
        - ReadWriteMany
  persistence:
    enabled: true
    storageClass: efs-sc
    accessModes: 
      - ReadWriteMany
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: dbi-eks-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/target-type: ip
    path: /
    hostname: fungjai-clickhouse.dbiteam.com


minio:
  enabled: true
  resources:
    requests:
      memory: 2Gi
  rootUser: rootuser
  rootPassword: rootpass123
  accessKey: mEOo8Tw0c1ZindTp
  secretKey: M0jGwjgT5eSAYt4d8HfrhwLaSZP14Fst
  mode: standalone
  replicas: 1
  persistence:
    enabled: true
    storageClass: efs-sc
    accessMode: ReadWriteMany
    size: 2Gi
  mountPath: /export
  certsPath: /etc/minio/certs/
  configPathmc: /etc/minio/mc/
  users: null
  securityContext:
    enabled: true
    runAsUser: 50008
    runAsGroup: 50008
    fsGroup: 50008
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: dbi-eks-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/target-type: ip
    path: /
    hosts:
      - fungjai-minio.dbiteam.com
  consoleIngress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/group.name: dbi-eks-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/target-type: ip
    path: /
    hosts:
      - fungjai-minio-console.dbiteam.com


metabase:
  replicaCount: 1
  service:
    port: 3000
    targetPort: 3000
  image:
    repository: 325067013020.dkr.ecr.ap-southeast-1.amazonaws.com/fungjai/metabase
    tag: "1.0.1"
    pullSecret: 
      name: regcred
  deploy:
    containerPort: 3000
  ingress:
    host: metabase.dbiteam.com


efs:
  id: fs-f92098b9