version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_REGION: ap-southeast-1
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./docker_data/minio:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    command: server /data --console-address ":9001"

  clickhouse-server:
    image: clickhouse/clickhouse-server:23.1.3.5-alpine
    hostname: clickhouse-server
    container_name: clickhouse-server
    ports:
      - 8123:8123
    volumes:
      - ./docker_data/clickhouse/server:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  metabase:
    image: 'metabase/metabase:v0.45.2.1'
    container_name: 'metabase-with-clickhouse'
    environment:
      MB_PLUGIN_CACHE_ENABLED: "false"
    hostname: metabase-moodytrack
    ports:
      - '3000:3000'
    volumes:
      - ./docker_data/metabase/plugins:/plugins
