apiVersion: v1
kind: Service
metadata:
  name: metabase-service
spec:
  selector: 
    app: fungjai-metabase
  ports:
  - port: {{ .Values.metabase.service.port }}
    targetPort: {{ .Values.metabase.service.targetPort }}
