apiVersion: v1
data:
  AIRFLOW_UID: NTAwMDA=
  BOOTSTRAP_SERVERS: ZnVuZ2phaS1rYWZrYS5mdW5namFpOjkwOTIK
  KAFKA_TOPIC_NAME: bW9vZF9yZXNwb25zZXM=
  CHANNEL_ACCESS_TOKEN: KyttZmVpVHIvYVlnUzJwc3hqRTdSSXFyWWZaL0drb0hzMDlOZXpZOGdNcDdXSG8yOHJMOWlqOUEwZDYvRGtHQkhNYnBaNXpPQnZaZmF4Smh5cUZveFpyMDRpRVZBaFhkemJFenpwWXpORG1ONUJkU3o4eHd3ZnFaUlZmVDNObjVVZzdETFRRQWRhZ0EwdnZZaTRYR0pBZEIwNHQ4OS8xTy93MWNEbnlpbEZVPQ==
  CHANNEL_SECRET: MGUzY2ZkYmE2NGQwOWViODJiYmQxZDJhOTY2MWM1NmQ=
  MINIO_ACCESS_KEY_ID: bUVPbzhUdzBjMVppbmRUcA==
  MINIO_SECRET_ACCESS_KEY: TTBqR3dqZ1Q1ZVNBWXQ0ZDhIZnJod0xhU1pQMTRGc3Q=
  
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-secrets