apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: dbi-eks-alb
    # alb.ingress.kubernetes.io/group.name: dbi-cluster-lb-dev
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: fungjai
spec:
  rules:
  - host: {{ .Values.webhook.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.webhook.service.name }}
            port:
              number: {{ .Values.webhook.service.port }}
        path: /
        pathType: Prefix