version: '3'

services:
  webhook:
    image: 266793978831.dkr.ecr.ap-southeast-1.amazonaws.com/fungjai/webhook:0.7.2
    container_name: docker-webhook
    ports:
      - "1323:1323"
    env_file:
      - .env

  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - './minio_data:/data'
    env_file:
      - .env
    command: server --console-address ":9090" /data