apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector: 
    app: fungjai-webhook
  ports:
  - port: 1323
    targetPort: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  selector:
    matchLabels:
      app: fungjai-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: fungjai-webhook
    spec:
      containers:
        - name: fungjai-webhook
          image: 266793978831.dkr.ecr.ap-southeast-1.amazonaws.com/fungjai/webhook:0.7.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: webhook-secrets
            - configMapRef:
                name: webhook-configmap
          ports: 
          - containerPort: 1323
      imagePullSecrets:
        - name: regcred