apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector: 
    app: fungjai-webhook
  ports:
  - port: 1323
    targetPort: 1323

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  selector:
    matchLabels:
      app: fungjai-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: fungjai-webhook
    spec:
      containers:
        - name: fungjai-webhook
          image: 266793978831.dkr.ecr.ap-southeast-1.amazonaws.com/fungjai/webhook:0.7.2
          imagePullPolicy: IfNotPresent
          env:
          - name: MINIO_ENDPOINT
            value: "10.244.0.154:9000"
          - name: MINIO_BUCKET_NAME
            value: "fungjai"
          - name: MINIO_LOCATION
            value: "ap-southeast-1"
          - name: MINIO_FOLDER_NAME
            value: "responses"
          - name: MINIO_RESPONSE_TYPE
            value: "mood"
          envFrom:
            - secretRef:
                name: webhook-secrets
          ports: 
          - containerPort: 1323
      imagePullSecrets:
        - name: regcred