apiVersion: v1
data:
  AIRFLOW_UID: NTAwMDA=
  BOOTSTRAP_SERVERS: bG9jYWxob3N0OjkwOTI=
  CHANNEL_ACCESS_TOKEN: IisrbWZlaVRyL2FZZ1MycHN4akU3UklxcllmWi9Ha29IczA5TmV6WThnTXA3V0hvMjhyTDlpajlBMGQ2L0RrR0JITWJwWjV6T0J2WmZheEpoeXFGb3hacjA0aUVWQWhYZHpiRXp6cFl6TkRtTjVCZFN6OHh3d2ZxWlJWZlQzTm41VWc3RExUUUFkYWdBMHZ2WWk0WEdKQWRCMDR0ODkvMU8vdzFjRG55aWxGVT0i
  CHANNEL_SECRET: IjBlM2NmZGJhNjRkMDllYjgyYmJkMWQyYTk2NjFjNTZkIg==
  MINIO_ACCESS_KEY_ID: ImxtZW5yTG50QzlsVGM5emYi
  MINIO_BUCKET_NAME: ImZ1bmdqYWki
  MINIO_ENDPOINT: IjEwLjI0NC4wLjY0OjkwMDAi
  MINIO_FOLDER_NAME: InJlc3BvbnNlcyI=
  MINIO_LOCATION: ImFwLXNvdXRoZWFzdC0xIg==
  MINIO_RESPONSE_TYPE: Im1vb2Qi
  MINIO_ROOT_PASSWORD: bWluaW8xMjNtYWs=
  MINIO_ROOT_USER: bWluaW8xMjM=
  MINIO_SECRET_ACCESS_KEY: InoydDRJcG1Jc1dMMTVBckJJdkNicWNRYnRLQ2pMWnNYIg==
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-secrets